import type {
  Account,
  Program,
  VolunteerRegistration,
  Certificate,
  ChatMessage,
  OrganizationRegistration,
} from "./types";

export const mockAccounts: Account[] = [
  {
    id: "vol-001",
    name: "Nguyễn Văn A",
    email: "nguyenvana@email.com",
    phone: "0901234567",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Kỹ sư phần mềm, đam mê chia sẻ kiến thức AI cho trẻ em",
    createdAt: "2024-01-15",
  },
  {
    id: "vol-002",
    name: "Trần Thị B",
    email: "tranthib@email.com",
    phone: "0912345678",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Giáo viên công nghệ, yêu thích dạy học cho trẻ em vùng cao",
    createdAt: "2024-02-20",
  },
  {
    id: "vol-003",
    name: "Lê Văn C",
    email: "levanc@email.com",
    phone: "0923456789",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Chuyên gia AI, muốn phổ cập công nghệ cho thế hệ trẻ",
    createdAt: "2024-03-10",
  },
  {
    id: "org-001",
    name: "Tổ chức Giáo dục AI Vùng Cao",
    email: "contact@aivungcao.org",
    phone: "0288888888",
    role: "organization",
    avatar: "/generic-organization-logo.png",
    bio: "Chuyên tổ chức các chương trình phổ cập kiến thức AI cho trẻ em vùng cao",
    createdAt: "2023-06-01",
  },
  {
    id: "org-002",
    name: "Trung tâm Công nghệ Số cho Trẻ em",
    email: "info@cntreem.org",
    phone: "0289999999",
    role: "organization",
    avatar: "/generic-organization-logo.png",
    bio: "Tổ chức giáo dục công nghệ và AI cho trẻ em vùng sâu vùng xa",
    createdAt: "2023-08-15",
  },
  {
    id: "admin-001",
    name: "Admin System",
    email: "admin@together.vn",
    phone: "0287777777",
    role: "admin",
    createdAt: "2023-01-01",
  },
];

export const mockPrograms: Program[] = [
  {
    id: "prog-001",
    name: "Khóa học AI cơ bản cho trẻ em vùng cao",
    description:
      "Chương trình dạy kiến thức AI cơ bản cho trẻ em từ 8-15 tuổi tại các vùng cao, giúp các em tiếp cận với công nghệ hiện đại",
    domesticDescription:
      "Khóa học AI cơ bản miễn phí cho trẻ em vùng cao tại Việt Nam, bao gồm lập trình cơ bản, machine learning và ứng dụng thực tế",
    isInternational: false,
    organizationId: "org-001",
    organizationName: "Tổ chức Giáo dục AI Vùng Cao",
    category: "Giáo dục AI",
    location: "Lào Cai, Sơn La, Điện Biên",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    duration: "9 tháng",
    schedule: ["Thứ 2", "Thứ 4", "Thứ 6"],
    timeSlots: "14:00 - 17:00",
    volunteersNeeded: 20,
    volunteersJoined: 12,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-002",
    name: "Lập trình Python cho trẻ em vùng núi",
    description:
      "Dạy lập trình Python từ cơ bản đến nâng cao cho trẻ em vùng núi, tạo nền tảng vững chắc cho tương lai công nghệ",
    domesticDescription:
      "Chương trình dạy lập trình Python cho trẻ em vùng núi, bao gồm các bài tập thực hành và dự án thực tế",
    isInternational: false,
    organizationId: "org-002",
    organizationName: "Trung tâm Công nghệ Số cho Trẻ em",
    category: "Lập trình",
    location: "Yên Bái, Tuyên Quang, Hà Giang",
    startDate: "2024-05-01",
    endDate: "2024-11-30",
    duration: "7 tháng",
    schedule: ["Thứ 3", "Thứ 5", "Chủ nhật"],
    timeSlots: "08:00 - 11:00",
    volunteersNeeded: 30,
    volunteersJoined: 22,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-003",
    name: "Workshop Machine Learning cho học sinh THCS",
    description:
      "Tổ chức các workshop về Machine Learning cho học sinh THCS vùng cao, giúp các em hiểu về trí tuệ nhân tạo",
    domesticDescription:
      "Chương trình workshop Machine Learning cho học sinh THCS tại các tỉnh vùng cao",
    isInternational: false,
    organizationId: "org-001",
    organizationName: "Tổ chức Giáo dục AI Vùng Cao",
    category: "Giáo dục AI",
    location: "Cao Bằng, Bắc Kạn, Lạng Sơn",
    startDate: "2024-03-15",
    endDate: "2024-12-31",
    duration: "9 tháng",
    schedule: ["Thứ 7", "Chủ nhật"],
    timeSlots: "09:00 - 12:00",
    volunteersNeeded: 15,
    volunteersJoined: 10,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-004",
    name: "Dự án AI thực tế: Nhận diện hình ảnh",
    description: "Hướng dẫn trẻ em xây dựng dự án AI nhận diện hình ảnh, áp dụng kiến thức vào thực tế",
    domesticDescription: "Dự án thực hành AI nhận diện hình ảnh cho trẻ em vùng cao",
    isInternational: false,
    organizationId: "org-002",
    organizationName: "Trung tâm Công nghệ Số cho Trẻ em",
    category: "Dự án AI",
    location: "Lai Châu, Điện Biên",
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    duration: "3 tháng",
    schedule: ["Thứ 2", "Thứ 4", "Thứ 6"],
    timeSlots: "14:00 - 17:00",
    volunteersNeeded: 25,
    volunteersJoined: 18,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-005",
    name: "Chương trình AI Quốc tế cho Trẻ em Đông Nam Á",
    description:
      "Chương trình hợp tác quốc tế phổ cập kiến thức AI cho trẻ em tại các nước Đông Nam Á",
    domesticDescription:
      "Chương trình giáo dục AI quốc tế hỗ trợ trẻ em tại các nước Đông Nam Á",
    internationalDescription:
      "Tham gia cùng đội ngũ quốc tế để phổ cập kiến thức AI và công nghệ cho trẻ em tại các nước đang phát triển ở Đông Nam Á",
    isInternational: true,
    organizationId: "org-001",
    organizationName: "Tổ chức Giáo dục AI Vùng Cao",
    category: "Giáo dục AI",
    location: "Việt Nam, Lào, Campuchia",
    startDate: "2024-07-01",
    endDate: "2024-12-31",
    duration: "6 tháng",
    schedule: ["Thứ 2", "Thứ 4", "Thứ 6"],
    timeSlots: "14:00 - 17:00",
    volunteersNeeded: 30,
    volunteersJoined: 20,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-006",
    name: "Khóa học Robotics và AI cho trẻ em",
    description: "Kết hợp học lập trình robot và AI, giúp trẻ em vùng cao tiếp cận công nghệ tiên tiến",
    domesticDescription: "Chương trình học Robotics và AI cho trẻ em vùng cao",
    internationalDescription:
      "Chương trình quốc tế về Robotics và AI cho trẻ em tại các vùng nông thôn và vùng cao",
    isInternational: true,
    organizationId: "org-002",
    organizationName: "Trung tâm Công nghệ Số cho Trẻ em",
    category: "Robotics & AI",
    location: "Việt Nam, Thái Lan",
    startDate: "2024-08-01",
    endDate: "2025-02-28",
    duration: "7 tháng",
    schedule: ["Thứ 3", "Thứ 5", "Thứ 7"],
    timeSlots: "09:00 - 12:00",
    volunteersNeeded: 35,
    volunteersJoined: 25,
    image: "/teaching-children.jpg",
    status: "active",
  },
];

export const mockRegistrations: VolunteerRegistration[] = [
  {
    id: "reg-001",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-001",
    programName: "Khóa học AI cơ bản cho trẻ em vùng cao",
    status: "approved",
    appliedDate: "2024-03-20",
    approvedDate: "2024-03-22",
    hoursContributed: 24,
  },
  {
    id: "reg-002",
    volunteerId: "vol-002",
    volunteerName: "Trần Thị B",
    programId: "prog-002",
    programName: "Lập trình Python cho trẻ em vùng núi",
    status: "pending",
    appliedDate: "2024-04-10",
  },
  {
    id: "reg-003",
    volunteerId: "vol-003",
    volunteerName: "Lê Văn C",
    programId: "prog-002",
    programName: "Lập trình Python cho trẻ em vùng núi",
    status: "approved",
    appliedDate: "2024-04-05",
    approvedDate: "2024-04-07",
    hoursContributed: 16,
  },
  {
    id: "reg-004",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-003",
    programName: "Workshop Machine Learning cho học sinh THCS",
    status: "approved",
    appliedDate: "2024-02-28",
    approvedDate: "2024-03-01",
    hoursContributed: 32,
  },
  {
    id: "reg-005",
    volunteerId: "vol-002",
    volunteerName: "Trần Thị B",
    programId: "prog-001",
    programName: "Khóa học AI cơ bản cho trẻ em vùng cao",
    status: "approved",
    appliedDate: "2024-03-25",
    approvedDate: "2024-03-27",
    hoursContributed: 18,
  },
];

export const mockCertificates: Certificate[] = [
  {
    id: "cert-001",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-001",
    programName: "Khóa học AI cơ bản cho trẻ em vùng cao",
    hoursContributed: 24,
    issuedDate: "2024-04-15",
    certificateNumber: "CERT-2024-001",
  },
  {
    id: "cert-002",
    volunteerId: "vol-003",
    volunteerName: "Lê Văn C",
    programId: "prog-002",
    programName: "Lập trình Python cho trẻ em vùng núi",
    hoursContributed: 16,
    issuedDate: "2024-05-20",
    certificateNumber: "CERT-2024-002",
  },
];

export const mockOrganizationRegistrations: OrganizationRegistration[] = [
  {
    id: "org-reg-001",
    organizationName: "Trung tâm Phát triển Công nghệ Trẻ em",
    email: "contact@cntreem.org",
    phone: "0291111111",
    bio: "Tổ chức chuyên về giáo dục công nghệ và AI cho trẻ em vùng cao",
    status: "pending",
    appliedDate: "2024-10-15",
  },
  {
    id: "org-reg-002",
    organizationName: "Quỹ Giáo dục AI Việt Nam",
    email: "support@aivietnam.org",
    phone: "0292222222",
    bio: "Hỗ trợ phổ cập kiến thức AI và công nghệ số cho trẻ em vùng sâu vùng xa",
    status: "pending",
    appliedDate: "2024-10-18",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Giáo dục AI Vùng Cao",
    userRole: "organization",
    message:
      "Chào các bạn tình nguyện viên! Chúng tôi rất vui khi có các bạn tham gia chương trình phổ cập AI cho trẻ em vùng cao.",
    timestamp: "2024-04-01T08:00:00",
  },
  {
    id: "msg-002",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Giáo dục AI Vùng Cao",
    userRole: "organization",
    message:
      "Buổi học AI hôm nay lúc 14:00 tại trường tiểu học Lào Cai. Các bạn nhớ mang theo laptop và tài liệu đã chuẩn bị nhé!",
    timestamp: "2024-04-01T11:00:00",
  },
  {
    id: "msg-003",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Giáo dục AI Vùng Cao",
    userRole: "organization",
    message:
      "Cảm ơn các bạn đã tham gia buổi học hôm nay. Các em học sinh rất hào hứng với bài học về Machine Learning!",
    timestamp: "2024-04-01T16:30:00",
  },
  {
    id: "msg-004",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Giáo dục AI Vùng Cao",
    userRole: "organization",
    message:
      "Tuần tới chúng ta sẽ có buổi học đặc biệt về 'AI nhận diện hình ảnh'. Các bạn chuẩn bị demo và ví dụ thực tế nhé!",
    timestamp: "2024-04-02T09:15:00",
  },
  {
    id: "msg-005",
    programId: "prog-002",
    userId: "org-002",
    userName: "Trung tâm Công nghệ Số cho Trẻ em",
    userRole: "organization",
    message:
      "Chào mừng các bạn đến với chương trình dạy Python cho trẻ em vùng núi! Chúng ta sẽ bắt đầu từ 8:00 sáng ngày mai.",
    timestamp: "2024-05-01T09:00:00",
  },
  {
    id: "msg-006",
    programId: "prog-002",
    userId: "org-002",
    userName: "Trung tâm Công nghệ Số cho Trẻ em",
    userRole: "organization",
    message:
      "Nhớ mang theo laptop và cài đặt Python sẵn. Chúng ta sẽ học tại trường THCS Yên Bái.",
    timestamp: "2024-05-01T14:20:00",
  },
  {
    id: "msg-007",
    programId: "prog-003",
    userId: "org-001",
    userName: "Tổ chức Giáo dục AI Vùng Cao",
    userRole: "organization",
    message:
      "Cảm ơn các bạn đã tham gia workshop Machine Learning. Hãy chuẩn bị các bài tập thực hành để các em học sinh có thể làm ngay tại lớp.",
    timestamp: "2024-03-15T10:00:00",
  },
];
